refactor.CI/CD 배포 자동화 테스트

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -19,10 +19,14 @@ jobs:
 
       - name: Commit and push changes to personal repository
         run: |
-          set -x  # Enable Bash debug mode
+          set -euxo pipefail  # Enable Bash debug mode, exit on error, unset variables, and trace commands
           export GIT_TRACE=1  # Enable Git trace
+          export GIT_CURL_VERBOSE=1  # Enable detailed cURL information
           git add .
           git commit -m "Automated commit message" || echo "No changes to commit"
-          git push https://$GH_PAT@github.com/JONGHYUNVAN/meta2day_front.git HEAD:main || echo "Push failed"
+          if ! git push https://$GH_PAT@github.com/JONGHYUNVAN/meta2day_front.git HEAD:main; then
+            echo "Push failed"
+            exit 1
+          fi
         env:
           GH_PAT: ${{ secrets.GH_PAT }}
